# Generated by Django 3.0.7 on 2020-09-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(default='Sep 12, 2020', max_length=12),
        ),
    ]
