# Generated by Django 3.0.7 on 2020-09-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Join',
        ),
    ]
