# Generated by Django 3.0.7 on 2020-09-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200922_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
