# Generated by Django 3.0.7 on 2020-09-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200922_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.CharField(default='Sep 09, 2020', max_length=12),
        ),
    ]
