# Generated by Django 3.0.7 on 2020-09-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200922_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
