# Generated by Django 3.0.7 on 2020-09-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_join_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='Applications',
        ),
    ]
