# Generated by Django 3.0.7 on 2020-09-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='joinyes',
            field=models.BooleanField(default=False),
        ),
    ]
