# Generated by Django 3.0.7 on 2020-09-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_application_joinyes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='joinyes',
        ),
    ]
