# Generated by Django 3.0.7 on 2020-09-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_application_joinyes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_poster',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
