# Generated by Django 3.0.7 on 2020-09-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blog_main_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='main_poster',
        ),
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
