# Generated by Django 3.1.2 on 2020-10-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_res'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Res',
        ),
    ]
