# Generated by Django 3.1.2 on 2020-10-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
